export const GET_LANGUAGE_RESOURCE_REQUEST = 'GET_LANGUAGERE_RESOURCE_REQUEST';
export const GET_USER_CONFIGURATION_REQUEST = 'GET_USER_CONFIGURATION_REQUEST';
export const GET_LANGUAGE_RESOURCE_SUCCESS = 'GET_LANGUAGERE_RESOURCE_SUCCESS';
export const GET_USER_CONFIGURATION_SUCCESS = 'GET_USER_CONFIGURATION_SUCCESS';
export const GET_LANGUAGE_RESOURCE_FAILURE = 'GET_LANGUAGERE_RESOURCE_FAILURE';
export const GET_USER_CONFIGURATION_FAILURE = 'GET_USER_CONFIGURATION_FAILURE';